### ISSUE TITLE
can it run in unbounded mode?

### ISSUE THREAD

**Issue by Hanming0209** [vuplex/visionos-mr-webview-example#3]
Hello, can it run with the unbounded mode? can scale the webview to any size? Your screenshot shows bounded mode,that means the content and webview size is limited,I want to scale the webview to very large

**Comment by binarynate** [comment]
Hi 👋🏻. Thank you for using 3D WebView! I really appreciate your business. Yes, the [VisionOSWebView.CreateInWindow()](https://developer.vuplex.com/webview/VisionOSWebView#CreateInWindow) API used by this example project can be used in unbounded mode. Regardless of whether the Unity scene uses bounded or unbounded mode, CreateInWindow() creates the webview in a native visionOS window that is not limited by the bounds of the Unity scene. For future question, please use the [Vuplex contact page](https://support.vuplex.com/contact). I will be disabling the Issues feature for this repo to ensure that support questions are directed through the contact page.
